### ISSUE TITLE
Is Possible to add this Source?

### ISSUE THREAD

**Issue by RizkyM2999** [hexated/cloudstream-extensions-hexated#318]
https://streamflix.in/

Its like Netflix Mirror but Bassed on App
Also have Dub and speed is good on me

**Comment by SaurabhKaperwan** [comment]
This app is 🔥

**Comment by aadio7** [comment]
The app is very good for hindi content as well as english

**Comment by aadio7** [comment]
> yeah its good.. but the application is a bit sus.. it want a lot of permission.. I know you can deny all of permission but it will good if added to CS

Ik i go to there telegram and asked them about that ... they want file and audio for audio search and profile photo

**Comment by hexated** [comment]
Added in sora for now. Not sure how long this can work

**Comment by aadio7** [comment]
> Added in sora for now. Not sure how long this can work

Is the source you named is SFMovies?

**Comment by hexated** [comment]
Yes

**Comment by aadio7** [comment]
> Yes

Idk if its possible but in streamflix there is some time 2 1080p which can specify which is higher quality since in streamflix app it shows 1080 then 4.smth Mbps and for another 2.smthng Mbps ... its also showing 1080p for which in app it shows hdr👍 idk no pressure on you for hdr but if somehow make it shows the streaming speed which shows on app it will be good

**Comment by aadio7** [comment]
> Yes

![Uploading Screenshot_20231014-175748_CloudStream Beta.jpg…]()  in 1080p one of them must be hdr,one be 1080high quality,one low quality
