### ISSUE TITLE
Anime Saga missing

### ISSUE THREAD

**Issue by HaxerAhmed** [hexated/cloudstream-extensions-hexated#628]
Anime saga is missing but new provider named 'anplay' is showing no link found. I tried vpn and also changed the dns but still not working
![Screenshot_2024-03-07-05-32-11-100_com android settings](https://github.com/hexated/cloudstream-extensions-hexated/assets/101901219/a78fc962-2924-4df7-9ab6-cb2659fcc767)

**Comment by phisher98** [comment]
@HaxerAhmed New name is Anplay for Animesaga so its changed now and its working fine and use Inbuild change Dns option instead of router dns change 
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/c779679d-8f3b-4de6-bd16-08cf3172d778)

need to change dns settings (general > dns over http) try Cloudflare option working fine

**Comment by HaxerAhmed** [comment]
Working now without changing anything 😁
